In [1]:
import pandas as pd

# Load the dataset
data = pd.read_excel("ToyotaCorolla.xlsx")
data.head()

,Id,Model,Price,Vehicle_Age,Mfg_Month,Mfg_Year,KM,Fuel_Type,HP,Met_Color,...,Powered_Windows,Power_Steering,Radio,Mistlamps,Sport_Model,Backseat_Divider,Metallic_Rim,Radio_cassette,Parking_Assistant,Tow_Bar
0,1,TOYOTA Corolla 2.0 D4D HATCHB TERRA 2/3-Doors,13500,23,10,2002,46986,Diesel,90,1,...,1,1,0,0,0,1,0,0,0,0
1,2,TOYOTA Corolla 2.0 D4D HATCHB TERRA 2/3-Doors,13750,23,10,2002,72937,Diesel,90,1,...,0,1,0,0,0,1,0,0,0,0
2,3,TOYOTA Corolla 2.0 D4D HATCHB TERRA 2/3-Doors,13950,24,9,2002,41711,Diesel,90,1,...,0,1,0,0,0,1,0,0,0,0
3,4,TOYOTA Corolla 2.0 D4D HATCHB TERRA 2/3-Doors,14950,26,7,2002,48000,Diesel,90,0,...,0,1,0,0,0,1,0,0,0,0
4,5,TOYOTA Corolla 2.0 D4D HATCHB SOL 2/3-Doors,13750,30,3,2002,38500,Diesel,90,0,...,1,1,0,1,0,1,0,0,0,0

In [3]:
# Step 1: Select only the relevant columns
data = data[['Price', 'Vehicle_Age', 'KM', 'Mfg_Year', 'Fuel_Type']]

# Step 2: Check for missing values
# This will help us see if there are any missing values in the selected columns
print("Missing values in each column:\n", data.isnull().sum())

# Step 3: Handle missing values (if any)
# In this case, let's drop rows with missing values in the selected columns
data = data.dropna()

# Step 4: Check data types of each column to ensure correctness
print("\nData types before conversion:\n", data.dtypes)

# Step 5: Convert categorical variable 'Fuel_Type' into dummy variables
# This is necessary for 'Fuel_Type' to be used in a linear regression model
data = pd.get_dummies(data, columns=['Fuel_Type'], drop_first=True)

# Step 6: Verify data after cleaning
print("\nData after cleaning:\n", data.head())
print("\nData types after conversion:\n", data.dtypes)

Missing values in each column:
 Price          0
Vehicle_Age    0
KM             0
Mfg_Year       0
Fuel_Type      0
dtype: int64

Data types before conversion:
 Price           int64
Vehicle_Age     int64
KM              int64
Mfg_Year        int64
Fuel_Type      object
dtype: object

Data after cleaning:
    Price  Vehicle_Age     KM  Mfg_Year  Fuel_Type_Diesel  Fuel_Type_Petrol
0  13500           23  46986      2002              True             False
1  13750           23  72937      2002              True             False
2  13950           24  41711      2002              True             False
3  14950           26  48000      2002              True             False
4  13750           30  38500      2002              True             False

Data types after conversion:
 Price               int64
Vehicle_Age         int64
KM                  int64
Mfg_Year            int64
Fuel_Type_Diesel     bool
Fuel_Type_Petrol     bool
dtype: object

In [13]:
# Step 1: Import Necessary Libraries and Set Up the Data

import statsmodels.api as sm

# Define independent variables (X) and dependent variable (y)
# We already have data cleaned and with dummy variables, so we can use it directly
X = data[['Vehicle_Age', 'KM', 'Mfg_Year', 'Fuel_Type_Diesel', 'Fuel_Type_Petrol']]
y = data['Price']

# Add a constant to the independent variables (required for statsmodels)
X = sm.add_constant(X)

In [17]:
# Convert boolean columns to integers
data['Fuel_Type_Diesel'] = data['Fuel_Type_Diesel'].astype(int)
data['Fuel_Type_Petrol'] = data['Fuel_Type_Petrol'].astype(int)

# Define X (independent variables) and y (dependent variable) again, just in case
X = data[['Vehicle_Age', 'KM', 'Mfg_Year', 'Fuel_Type_Diesel', 'Fuel_Type_Petrol']]
y = data['Price']

# Add a constant to the independent variables
X = sm.add_constant(X)

# Fit the linear regression model
model = sm.OLS(y, X).fit()

# Display model summary
print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                  Price   R-squared:                       0.808
Model:                            OLS   Adj. R-squared:                  0.807
Method:                 Least Squares   F-statistic:                     1200.
Date:                Thu, 07 Nov 2024   Prob (F-statistic):               0.00
Time:                        10:01:14   Log-Likelihood:                -12624.
No. Observations:                1436   AIC:                         2.526e+04
Df Residuals:                    1430   BIC:                         2.529e+04
Df Model:                           5
Covariance Type:            nonrobust
====================================================================================
                       coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------
const            -3.157e+06   3.04e+05    -10.371      0.000   -3.75e+06   -2.56e+06
Vehicle_Age        -20.6262     12.657     -1.630      0.103     -45.454       4.201
KM                  -0.0195      0.002    -12.431      0.000      -0.023      -0.016
Mfg_Year          1585.4440    151.895     10.438      0.000    1287.482    1883.406
Fuel_Type_Diesel   958.9086    407.446      2.353      0.019     159.652    1758.166
Fuel_Type_Petrol   200.9875    398.807      0.504      0.614    -581.322     983.297
==============================================================================
Omnibus:                      371.169   Durbin-Watson:                   1.263
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             3078.384
Skew:                           0.963   Prob(JB):                         0.00
Kurtosis:                       9.909   Cond. No.                     5.66e+08
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 5.66e+08. This might indicate that there are
strong multicollinearity or other numerical problems.